# Generated by Django 4.2 on 2023-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_querycount'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTodayCount',
            fields=[
                ('curr_date', models.DateField(primary_key=True, serialize=False)),
                ('today_total', models.IntegerField()),
            ],
        ),
    ]
